safe: true
markdown: kramdown
highlighter: pygments
permalink: /:title.html
relative_permalinks: false

default_theme: ribbon
default_width: 792
default_lang: en
default_body_class: list

author:
    name: Vit Karpov
    url:  http://vitkarpov.com/
    company:
        name: Yandex

fork_url: https://github.com/vitkarpov/jekyller
progress: true
line_numbers: true
